CREATE DATABASE IF NOT EXISTS localshop_school CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE localshop_school;

CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  category ENUM('Mushroom','Frog','Vegetable','Egg','Fish') NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  unit VARCHAR(20) NOT NULL DEFAULT 'kg',
  stock INT NOT NULL DEFAULT 0,
  image_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  buyer_name VARCHAR(120) NOT NULL,
  phone VARCHAR(32),
  product_id INT NOT NULL,
  qty INT NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  status ENUM('NEW','CONFIRMED','CANCELLED') DEFAULT 'NEW',
  trace_id VARCHAR(36) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  INDEX idx_trace_id (trace_id)
);

CREATE TABLE IF NOT EXISTS media (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL,
  url VARCHAR(255) NOT NULL,
  caption VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
